In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

## Datatypes and attributes

In [3]:
# NumPy's main datetype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.shape

(3,)

In [6]:
a1.ndim

1

In [7]:
a1.dtype

dtype('int32')

In [8]:
a1.size

3

In [11]:
ones = np.ones((3, 4), 'int32')

In [12]:
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
range_array = np.arange(20, 45, 3)
range_array

array([20, 23, 26, 29, 32, 35, 38, 41, 44])

In [22]:
random_array = np.random.randint(0, 10, size=(5, 2, 2))
random_array

array([[[1, 6],
        [9, 9]],

       [[2, 9],
        [1, 6]],

       [[1, 1],
        [9, 8]],

       [[8, 7],
        [8, 7]],

       [[2, 2],
        [8, 0]]])

In [23]:
random2 = np.random.random((3,5))
random2

array([[0.4941267 , 0.34702447, 0.07714182, 0.52024224, 0.59643889],
       [0.39700282, 0.98377801, 0.64166744, 0.02100648, 0.30336167],
       [0.0283089 , 0.95492043, 0.97265491, 0.40265084, 0.64663929]])

In [24]:
np.random.rand(5,3)

array([[0.4640884 , 0.59689433, 0.42095394],
       [0.68078973, 0.28639527, 0.14873456],
       [0.8534355 , 0.65299503, 0.60520283],
       [0.88595391, 0.97973301, 0.70673878],
       [0.33214057, 0.04617339, 0.99586566]])

In [33]:
np.random.seed()
arr = np.random.randint(10, size=(5,3))
arr
#preudo-random (první stisknutí buňky (0) zůstane) -> aby měl někdo jiný stejný výsledek

array([[0, 1, 8],
       [3, 5, 6],
       [7, 0, 4],
       [0, 9, 2],
       [1, 9, 9]])

In [ ]:
## Viewing arrays and matrices